name: Deploy Demo to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build library
        run: pnpm run -r --filter=!demo build

      - name: Build demo
        run: pnpm --filter demo build
        env:
          GITHUB_PAGES: true

      - uses: actions/configure-pages@v5
        with:
          enablement: true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/demo/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
